apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome
spec:
  replicas: 3
  selector:
    matchLabels:
      app: selenium-node-chrome
  template:
    metadata:
      labels:
        app: selenium-node-chrome
    spec:
      containers:
      - name: selenium-node-chrome
        image: selenium/node-chrome:latest
        env:
        - name: HUB_HOST
          value: "selenium-hub"
        - name: HUB_PORT
          value: "4444"
        ports:
        - containerPort: 5555
